import "./css/style.css";

import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Link from "next/link";

import Header from "@/components/ui/header";
import Banner from "@/components/banner";
import { BsRobot } from "react-icons/bs";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
                >
                    <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
                        <Header />
                        {children}
                        {/* <Banner /> */}
                        {/* <Chat /> */}
                        <Link href="/chat">
                            <BsRobot className="bg-gradient-to-br from-blue-500 to-teal-400 text-black border border-gray-200 shadow-md animate-float fixed bottom-3 right-4 h-12 w-12 p-2 rounded-md" />
                        </Link>
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}
